version: "3.3"

services:
  redis:
    image: redis:7.0.9-alpine
    ports:
      - 6379:6379
    networks:
      - default
  traefik:
    image: traefik:v2.9.9
    ports:
      - 8080:8080
    volumes:
      - ./contrib/traefik:/etc/traefik
    networks:
      - default

  nats:
    image: nats:2.8
    networks:
      - default

  vault:
    image: hashicorp/vault:1.13
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "pleaseChangeMe"
      VAULT_LOG_LEVEL: "debug"
      # To setup your dev instance:
      # docker exec -it <my vault> sh
      # export VAULT_PASSWORD="<see your .env>"
      # /tmp/setup
    volumes:
      - ./contrib/vault:/tmp:rw
    cap_add:
      - IPC_LOCK
    networks:
      - default

volumes:
  data:
